# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.12"      # put version as string
  install:
    - requirements: docs/requirements.txt

formats:
  - html